### ISSUE TITLE
Issues with understanding `winit_polling_event_loop_new_with_semaphore_and_main_events_signaller` function

### ISSUE THREAD

**Issue by VarLad** [feenkcom/libwinit#2]
@syrel I've been using libwinit in C with a header file I wrote 
Can you explain the parameters being in used in the function?
Here's the definition https://github.com/feenkcom/libwinit/blob/e55e8c2249dd91ef5d3c894bfd7c4563f4f3a5cd/library/src/ffi/polling_event_loop.rs#L79

**Comment by VarLad** [comment]
Trying to rewrite https://github.com/rust-windowing/winit/blob/master/examples/window.rs in C using the header file. 
Any help with that? 
Also, can I make a PR to submit the C header file? :)

**Comment by syrel** [comment]
Hi @VarLad 

Thanks for the question! I will follow up here

**Comment by syrel** [comment]
@VarLad I have added a sample C project here: https://github.com/feenkcom/libwinit/tree/main/examples/c-api
`winit_polling_event_loop_new_with_semaphore_and_main_events_signaller` creates an event loop that signals a semaphore in a GToolkit VM 😃 I am not sure it is interesting otherwise. Take a look at the sample project and let me know if you need more winit api to be exposed.

**Comment by syrel** [comment]
I will close this one for now. Feel free to open more follow-up issues

**Comment by VarLad** [comment]
@syrel Thanks a lot!
My issue with the main.c file is, how do we do the redrawing part given in https://github.com/rust-windowing/winit/blob/master/examples/window.rs#L29
with libwinit?
